### ISSUE TITLE
[QUESTION]: Is the helpers directory only for handlebars helpers?

### ISSUE THREAD

**Issue by williamsbdev** [stefanpenner/ember-cli-auto-register-helpers#2]
I know our team sometimes will put other functions into the helpers directory. Is the convention of ember-cli to save the helpers directory for handlebars (htmlbars now) helpers only?

**Comment by rwjblue** [comment]
That is the assumption that this addon makes, yes.  I personally put helper functions (but not template helpers) into `app/utils/`...

**Comment by williamsbdev** [comment]
Very good. I will transition to that. Thanks @rwjblue!
